/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.css;

import java.awt.CardLayout;

/**
 *
 * @author gabe
 */
public class PSSGUI extends javax.swing.JFrame {

    PSS pss = new PSS(); // Create an instance of the scheduling program
    
    /**
     * Creates new form PSSGUI
     */
    public PSSGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        addTask = new javax.swing.JButton();
        removeTask = new javax.swing.JButton();
        editTask = new javax.swing.JButton();
        readTasks = new javax.swing.JButton();
        searchTask = new javax.swing.JButton();
        writeToFile = new javax.swing.JButton();
        readFromFile = new javax.swing.JButton();
        viewSchedule = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        addTaskPanel = new javax.swing.JPanel();
        removeTaskPanel = new javax.swing.JPanel();
        editTaskPanel = new javax.swing.JPanel();
        readTasksPanel = new javax.swing.JPanel();
        searchTaskPanel = new javax.swing.JPanel();
        writeToFilePanel = new javax.swing.JPanel();
        readFromFilePanel = new javax.swing.JPanel();
        viewSchedulePanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        daySchedule = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dayScheduleText = new javax.swing.JTextArea();
        weekSchedule = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        weekScheduleText = new javax.swing.JTextArea();
        monthSchedule = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        monthScheduleText = new javax.swing.JTextArea();
        startDate = new javax.swing.JTextField();
        schedulePrompt = new javax.swing.JLabel();
        scheduleGenerateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group10Scheduler");

        buttonPanel.setBackground(new java.awt.Color(153, 153, 153));

        addTask.setText("Add Task");
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });

        removeTask.setText("Remove Task");
        removeTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTaskActionPerformed(evt);
            }
        });

        editTask.setText("Edit Task");
        editTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskActionPerformed(evt);
            }
        });

        readTasks.setText("Read Tasks");
        readTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readTasksActionPerformed(evt);
            }
        });

        searchTask.setText("Search Task");
        searchTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTaskActionPerformed(evt);
            }
        });

        writeToFile.setText("Write to File");
        writeToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeToFileActionPerformed(evt);
            }
        });

        readFromFile.setText("Read from File");
        readFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readFromFileActionPerformed(evt);
            }
        });

        viewSchedule.setText("View Schedule");
        viewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(writeToFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readFromFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readTasks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writeToFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readFromFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        addTaskPanel.setBackground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout addTaskPanelLayout = new javax.swing.GroupLayout(addTaskPanel);
        addTaskPanel.setLayout(addTaskPanelLayout);
        addTaskPanelLayout.setHorizontalGroup(
            addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        addTaskPanelLayout.setVerticalGroup(
            addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(addTaskPanel, "addTaskPanel");

        removeTaskPanel.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout removeTaskPanelLayout = new javax.swing.GroupLayout(removeTaskPanel);
        removeTaskPanel.setLayout(removeTaskPanelLayout);
        removeTaskPanelLayout.setHorizontalGroup(
            removeTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        removeTaskPanelLayout.setVerticalGroup(
            removeTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(removeTaskPanel, "removeTaskPanel");

        editTaskPanel.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout editTaskPanelLayout = new javax.swing.GroupLayout(editTaskPanel);
        editTaskPanel.setLayout(editTaskPanelLayout);
        editTaskPanelLayout.setHorizontalGroup(
            editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        editTaskPanelLayout.setVerticalGroup(
            editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(editTaskPanel, "editTaskPanel");

        javax.swing.GroupLayout readTasksPanelLayout = new javax.swing.GroupLayout(readTasksPanel);
        readTasksPanel.setLayout(readTasksPanelLayout);
        readTasksPanelLayout.setHorizontalGroup(
            readTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        readTasksPanelLayout.setVerticalGroup(
            readTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(readTasksPanel, "readTasksPanel");

        javax.swing.GroupLayout searchTaskPanelLayout = new javax.swing.GroupLayout(searchTaskPanel);
        searchTaskPanel.setLayout(searchTaskPanelLayout);
        searchTaskPanelLayout.setHorizontalGroup(
            searchTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        searchTaskPanelLayout.setVerticalGroup(
            searchTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(searchTaskPanel, "searchTaskPanel");

        javax.swing.GroupLayout writeToFilePanelLayout = new javax.swing.GroupLayout(writeToFilePanel);
        writeToFilePanel.setLayout(writeToFilePanelLayout);
        writeToFilePanelLayout.setHorizontalGroup(
            writeToFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        writeToFilePanelLayout.setVerticalGroup(
            writeToFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(writeToFilePanel, "writeToFilePanel");

        javax.swing.GroupLayout readFromFilePanelLayout = new javax.swing.GroupLayout(readFromFilePanel);
        readFromFilePanel.setLayout(readFromFilePanelLayout);
        readFromFilePanelLayout.setHorizontalGroup(
            readFromFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        readFromFilePanelLayout.setVerticalGroup(
            readFromFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        mainPanel.add(readFromFilePanel, "readFromFilePanel");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        daySchedule.setBackground(new java.awt.Color(204, 204, 255));

        dayScheduleText.setColumns(20);
        dayScheduleText.setRows(5);
        jScrollPane1.setViewportView(dayScheduleText);

        javax.swing.GroupLayout dayScheduleLayout = new javax.swing.GroupLayout(daySchedule);
        daySchedule.setLayout(dayScheduleLayout);
        dayScheduleLayout.setHorizontalGroup(
            dayScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );
        dayScheduleLayout.setVerticalGroup(
            dayScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dayScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Day", daySchedule);

        weekSchedule.setBackground(new java.awt.Color(204, 204, 255));

        weekScheduleText.setColumns(20);
        weekScheduleText.setRows(5);
        jScrollPane2.setViewportView(weekScheduleText);

        javax.swing.GroupLayout weekScheduleLayout = new javax.swing.GroupLayout(weekSchedule);
        weekSchedule.setLayout(weekScheduleLayout);
        weekScheduleLayout.setHorizontalGroup(
            weekScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weekScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );
        weekScheduleLayout.setVerticalGroup(
            weekScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weekScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Week", weekSchedule);

        monthSchedule.setBackground(new java.awt.Color(204, 204, 255));

        monthScheduleText.setColumns(20);
        monthScheduleText.setRows(5);
        jScrollPane3.setViewportView(monthScheduleText);

        javax.swing.GroupLayout monthScheduleLayout = new javax.swing.GroupLayout(monthSchedule);
        monthSchedule.setLayout(monthScheduleLayout);
        monthScheduleLayout.setHorizontalGroup(
            monthScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );
        monthScheduleLayout.setVerticalGroup(
            monthScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Month", monthSchedule);

        startDate.setText("YYYY-MM-DD");
        startDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateActionPerformed(evt);
            }
        });

        schedulePrompt.setText("Enter Starting Date:");

        scheduleGenerateButton.setText("Generate Schedules");
        scheduleGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleGenerateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewSchedulePanelLayout = new javax.swing.GroupLayout(viewSchedulePanel);
        viewSchedulePanel.setLayout(viewSchedulePanelLayout);
        viewSchedulePanelLayout.setHorizontalGroup(
            viewSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(viewSchedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSchedulePanelLayout.createSequentialGroup()
                        .addComponent(schedulePrompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scheduleGenerateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewSchedulePanelLayout.setVerticalGroup(
            viewSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewSchedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewSchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedulePrompt)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scheduleGenerateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(viewSchedulePanel, "viewSchedulePanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        layout.show(mainPanel, "addTaskPanel");
    }//GEN-LAST:event_addTaskActionPerformed

    private void removeTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTaskActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "removeTaskPanel");
    }//GEN-LAST:event_removeTaskActionPerformed

    private void editTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "editTaskPanel");
    }//GEN-LAST:event_editTaskActionPerformed

    private void readTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readTasksActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "readTasksPanel");
    }//GEN-LAST:event_readTasksActionPerformed

    private void searchTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTaskActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "searchTaskPanel");
    }//GEN-LAST:event_searchTaskActionPerformed

    private void writeToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeToFileActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "writeToFilePanel");
    }//GEN-LAST:event_writeToFileActionPerformed

    private void readFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readFromFileActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "readFromFilePanel");
    }//GEN-LAST:event_readFromFileActionPerformed

    private void viewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewScheduleActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "viewSchedulePanel");
    }//GEN-LAST:event_viewScheduleActionPerformed

    private void scheduleGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleGenerateButtonActionPerformed
        dayScheduleText.append(pss.showScheduleDay(startDate.getText()));
        weekScheduleText.append(pss.showScheduleWeek(startDate.getText()));
        monthScheduleText.append(pss.showScheduleWeek(startDate.getText()));

    }//GEN-LAST:event_scheduleGenerateButtonActionPerformed

    private void startDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PSSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PSSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PSSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //adding one task per day starting from 2024-12-01
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PSSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTask;
    private javax.swing.JPanel addTaskPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel daySchedule;
    private javax.swing.JTextArea dayScheduleText;
    private javax.swing.JButton editTask;
    private javax.swing.JPanel editTaskPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel monthSchedule;
    private javax.swing.JTextArea monthScheduleText;
    private javax.swing.JButton readFromFile;
    private javax.swing.JPanel readFromFilePanel;
    private javax.swing.JButton readTasks;
    private javax.swing.JPanel readTasksPanel;
    private javax.swing.JButton removeTask;
    private javax.swing.JPanel removeTaskPanel;
    private javax.swing.JButton scheduleGenerateButton;
    private javax.swing.JLabel schedulePrompt;
    private javax.swing.JButton searchTask;
    private javax.swing.JPanel searchTaskPanel;
    private javax.swing.JTextField startDate;
    private javax.swing.JButton viewSchedule;
    private javax.swing.JPanel viewSchedulePanel;
    private javax.swing.JPanel weekSchedule;
    private javax.swing.JTextArea weekScheduleText;
    private javax.swing.JButton writeToFile;
    private javax.swing.JPanel writeToFilePanel;
    // End of variables declaration//GEN-END:variables
}
